name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get install -y clang-tidy clang-format
      - run: find . -path './build' -prune -o -type f \( -name '*.c' -o -name '*.h' \) -print0 | \
            xargs -0 -I{} clang-format --dry-run --Werror {}
      - run: find . -name '*.c' -not -path './build/*' -print0 | xargs -0 -I{} clang-tidy {} \
            -- --target=arm-none-eabi -march=armv7-m -isystem /usr/arm-none-eabi/include \
            -std=c11 -I./include